services:
  swag:
    image: lscr.io/linuxserver/swag #base image
    container_name: swag #name of container
    hostname: swag #name of virtual pc on network
    cap_add: #additional linux permissions
      - NET_ADMIN #for fail2ban ig?
    networks: #custom networks
      - webserver 
    env_file:
      - .env
    environment: #environment variables
      - PUID=1001 #run the program as this user
      - PGID=1001 #group permissions for the program
      - TZ=Asia/Kolkata #timezone
      - VALIDATION=dns #certbot validation type
      - DNSPLUGIN=cloudflare #cloudflare is dns provider
      - PROPAGATION=30 #wait 30s b4 checking dns challenge
      - ONLY_SUBDOMAINS=false #include base domain as well
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload #add dashboard for monitoring swag
    volumes: #persistent storage [source_on_host:destination_in_container]
      - ./swag_config:/config #configration files
      - /home/bv/website:/config/www #html website for www.beevee.ga
      - /home/bv/Downloads/complete/LLaMA:/config/www/LLaMA 
      - ../jellyfin/jellyfin-config/log:/f2b_log/jellyfin:ro #logs from jellyfin for fail2ban
      - ../vaultwarden/vw-data/vaultwarden.log:/f2b_log/vaultwarden/vaultwarden.log:ro #logs from vaultwarden for fail2ban
      - /home/bv/data/nextcloud/nextcloud.log:/f2b_log/nextcloud/nextcloud.log:ro #logs from nextcloud for fail2ban
    ports: #expose ports 
      - 443:443 #https
      - 80:80 #http for redirection and certbot
    restart: unless-stopped #automatically restart 
    
networks: #define custom networks
  webserver:  
     external: true #use predefined network
