services:
  transmission:
    image: lscr.io/linuxserver/transmission #base image
    container_name: transmission #name of container
    hostname: transmission #name of virtual pc on network
    networks: #custom networks
      - webserver
    env_file: #sensitive environment variables in file 
      - .env
    environment: #environment variables
      - PUID=1001 #run the program as this user
      - PGID=1001 #group permissions for the program
      - TZ=Asia/Kolkata #timezone
      - DOCKER_MODS=linuxserver/mods:transmission-floodui #using the flood ui, combustion is better for mobile centric
    volumes: #persistent storage [source_on_host:destination_in_container]
      - ./transmission-config:/config #configration files
      - ${HOME}/Downloads:/downloads #default location to download to
      - ${HOME}/OS_ISO:/OS_ISO #changed ISO download location
      - ${HOME}/media:/media #wtf does it do, idk :)
      - ${HOME}/torrent-watch:/watch #watch directory for torrent files to autodownload
    ports: #expose ports 
      - 51413:51413 #peer listen port
      - 51413:51413/udp #peer listen port
    restart: unless-stopped #automatically restart 

networks: #define custom networks
  webserver:
    external: true #use predefined network
