services:
  mariadb: #mysql-like database
    image: lscr.io/linuxserver/mariadb #base image
    container_name: nc_db #name of container
    hostname: nc_db #name of virtual pc on network
    networks: #custom networks
      - db
    env_file: #sensitive environment variables in file 
      - .env
    environment: #environment variables
      - PUID=1001 #run the program as this user
      - PGID=1001 #group permissions for the program
      - TZ=Asia/Kolkata #timezone
    volumes: #persistent storage [source_on_host:destination_in_container]
      - ./mariadb-config:/config #configration files
    restart: unless-stopped #automatically restart 

  redis: #distributed cache to speed-up database
    image: redis:alpine #base image
    container_name: nc_redis #name of container
    hostname: nc_redis #name of virtual pc on network
    user: 1001:1001 #run everything in container as user
    networks: #custom networks
      - db
    volumes: #persistent storage [source_on_host:destination_in_container]
      - ./redis-data:/data #data files
    restart: unless-stopped #automatically restart 

  nextcloud:
    image: lscr.io/linuxserver/nextcloud #base image
    container_name: nextcloud #name of container
    hostname: nextcloud #name of virtual pc on network
    networks: #custom networks
      - webserver
      - db
    env_file: #sensitive environment variables in file 
      - .env
    environment: #environment variables
      - PUID=1001 #run the program as this user
      - PGID=1001 #group permissions for the program
      - TZ=Asia/Kolkata #timezone
      - MYSQL_HOST=nc_mariadb #hostname of database
      - REDIS_HOST=nc_redis #hostname of redis cache
    volumes: #persistent storage [source_on_host:destination_in_container]
      - ./nextcloud-config:/config #configration files
      - ${HOME}/data/nextcloud:/data #data storage for nextcloud
      - ${HOME}/bogosbinted:/Photos #attached for external storage for photoprism import
    depends_on: #needs these containers to be running first
      - mariadb
      - redis
    restart: unless-stopped #automatically restart 
  
  code: #office suite
    image: collabora/code #base image
    container_name: collabora #name of container
    hostname: collabora #name of virtual pc on network
    networks: #custom networks
      - webserver 
    env_file: #sensitive environment variables in file 
      - .env
    environment: #environment variables
      - "aliasgroup1=https://nc\\.hbv\\.io\\.in:443" #only this (sub)domain can provide docs to collabora, "\\." mandatory for <dots>
      - "dictionaries=en_GB en_US" #only english spellcheck added
    volumes:
       - ./fonts:/opt/collaboraoffice/share/fonts/truetype/local #additional (ms) fonts
    restart: unless-stopped #automatically restart 
  
networks: #define custom networks
  webserver:
    external: true #use predefined network
  db: #create additional network only for database access
